#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="schoolSystem")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertMateria(Materia instance);
    partial void UpdateMateria(Materia instance);
    partial void DeleteMateria(Materia instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Model.Properties.Settings.Default.schoolSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Aluno
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Curso
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<Materia> Materia
		{
			get
			{
				return this.GetTable<Materia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aluno")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAluno;
		
		private string _Nome;
		
		private string _Endereco;
		
		private string _Cep;
		
		private string _Telefone;
		
		private string _Celular;
		
		private System.Nullable<System.DateTime> _dataNascimento;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _dataAtualizacao;
		
		private EntitySet<Curso> _Curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAlunoChanging(int value);
    partial void OnidAlunoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCepChanging(string value);
    partial void OnCepChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OndataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OndataNascimentoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OndataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAtualizacaoChanged();
    #endregion
		
		public Aluno()
		{
			this._Curso = new EntitySet<Curso>(new Action<Curso>(this.attach_Curso), new Action<Curso>(this.detach_Curso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAluno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAluno
		{
			get
			{
				return this._idAluno;
			}
			set
			{
				if ((this._idAluno != value))
				{
					this.OnidAlunoChanging(value);
					this.SendPropertyChanging();
					this._idAluno = value;
					this.SendPropertyChanged("idAluno");
					this.OnidAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(255)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cep", DbType="VarChar(17)")]
		public string Cep
		{
			get
			{
				return this._Cep;
			}
			set
			{
				if ((this._Cep != value))
				{
					this.OnCepChanging(value);
					this.SendPropertyChanging();
					this._Cep = value;
					this.SendPropertyChanged("Cep");
					this.OnCepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(17)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(17)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataNascimento", DbType="Date")]
		public System.Nullable<System.DateTime> dataNascimento
		{
			get
			{
				return this._dataNascimento;
			}
			set
			{
				if ((this._dataNascimento != value))
				{
					this.OndataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._dataNascimento = value;
					this.SendPropertyChanged("dataNascimento");
					this.OndataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAtualizacao
		{
			get
			{
				return this._dataAtualizacao;
			}
			set
			{
				if ((this._dataAtualizacao != value))
				{
					this.OndataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._dataAtualizacao = value;
					this.SendPropertyChanged("dataAtualizacao");
					this.OndataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Curso", Storage="_Curso", ThisKey="idAluno", OtherKey="idAluno")]
		public EntitySet<Curso> Curso
		{
			get
			{
				return this._Curso;
			}
			set
			{
				this._Curso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Curso(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Curso(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCurso;
		
		private int _idAluno;
		
		private int _idMateria;
		
		private string _Nome;
		
		private string _Descricao;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _dataAtualizacao;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Materia> _Materia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCursoChanging(int value);
    partial void OnidCursoChanged();
    partial void OnidAlunoChanging(int value);
    partial void OnidAlunoChanged();
    partial void OnidMateriaChanging(int value);
    partial void OnidMateriaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OndataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAtualizacaoChanged();
    #endregion
		
		public Curso()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Materia = default(EntityRef<Materia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCurso
		{
			get
			{
				return this._idCurso;
			}
			set
			{
				if ((this._idCurso != value))
				{
					this.OnidCursoChanging(value);
					this.SendPropertyChanging();
					this._idCurso = value;
					this.SendPropertyChanged("idCurso");
					this.OnidCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAluno", DbType="Int NOT NULL")]
		public int idAluno
		{
			get
			{
				return this._idAluno;
			}
			set
			{
				if ((this._idAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAlunoChanging(value);
					this.SendPropertyChanging();
					this._idAluno = value;
					this.SendPropertyChanged("idAluno");
					this.OnidAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateria", DbType="Int NOT NULL")]
		public int idMateria
		{
			get
			{
				return this._idMateria;
			}
			set
			{
				if ((this._idMateria != value))
				{
					if (this._Materia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMateriaChanging(value);
					this.SendPropertyChanging();
					this._idMateria = value;
					this.SendPropertyChanged("idMateria");
					this.OnidMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAtualizacao
		{
			get
			{
				return this._dataAtualizacao;
			}
			set
			{
				if ((this._dataAtualizacao != value))
				{
					this.OndataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._dataAtualizacao = value;
					this.SendPropertyChanged("dataAtualizacao");
					this.OndataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Curso", Storage="_Aluno", ThisKey="idAluno", OtherKey="idAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Curso.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Curso.Add(this);
						this._idAluno = value.idAluno;
					}
					else
					{
						this._idAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Curso", Storage="_Materia", ThisKey="idMateria", OtherKey="idMateria", IsForeignKey=true)]
		public Materia Materia
		{
			get
			{
				return this._Materia.Entity;
			}
			set
			{
				Materia previousValue = this._Materia.Entity;
				if (((previousValue != value) 
							|| (this._Materia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Materia.Entity = null;
						previousValue.Curso.Remove(this);
					}
					this._Materia.Entity = value;
					if ((value != null))
					{
						value.Curso.Add(this);
						this._idMateria = value.idMateria;
					}
					else
					{
						this._idMateria = default(int);
					}
					this.SendPropertyChanged("Materia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materia")]
	public partial class Materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMateria;
		
		private string _Nome;
		
		private string _Descricao;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _dataAtualizacao;
		
		private EntitySet<Curso> _Curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMateriaChanging(int value);
    partial void OnidMateriaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OndataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAtualizacaoChanged();
    #endregion
		
		public Materia()
		{
			this._Curso = new EntitySet<Curso>(new Action<Curso>(this.attach_Curso), new Action<Curso>(this.detach_Curso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMateria
		{
			get
			{
				return this._idMateria;
			}
			set
			{
				if ((this._idMateria != value))
				{
					this.OnidMateriaChanging(value);
					this.SendPropertyChanging();
					this._idMateria = value;
					this.SendPropertyChanged("idMateria");
					this.OnidMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAtualizacao
		{
			get
			{
				return this._dataAtualizacao;
			}
			set
			{
				if ((this._dataAtualizacao != value))
				{
					this.OndataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._dataAtualizacao = value;
					this.SendPropertyChanged("dataAtualizacao");
					this.OndataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Curso", Storage="_Curso", ThisKey="idMateria", OtherKey="idMateria")]
		public EntitySet<Curso> Curso
		{
			get
			{
				return this._Curso;
			}
			set
			{
				this._Curso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Curso(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Materia = this;
		}
		
		private void detach_Curso(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Materia = null;
		}
	}
}
#pragma warning restore 1591
